# Project information
site_name: !ENV [SITE_NAME, "Plebnet Compose"]

# Repository
repo_name: plebnet-compose
repo_url: https://github.com/plebnet-dev/plebnet-compose.git
edit_uri: ""

nav:
  - Home: index.md
  - Motivation: motivation.md
  - Images: images.md
  - Build: build.md
  - Run: run.md
  - Compose: compose.md
  - Environment: environment.md
  - Volumes: volumes.md
  - Network: network.md
  - Dashboard: dashboard.md
  - WorkLog: worklog.md

extra_watch_dirs:
  - ..

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


use_directory_urls: false

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

